# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bikesharingweb:
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik 
    hosts:
      - dev.bikesharingweb.<REPLACE_ME_WITH_HOST_SUFFIX>  # Assumes deployment to the 'dev' namespace

gateway:
  ingress:
    enabled: false
  ingressRoute:
    enabled: true
    path: /api
    stripPrefix: false