version: '3.4' 

services:

  bikes:
    image: bikeshare/bikesharing-bikes:dev
    build:
      context: samples/BikeSharingApp/Bikes

  bikeSharingWeb:
      image: bikeshare/bikesharing-bikesharingweb:dev
      build:
        context: samples/BikeSharingApp/BikeSharingWeb
  
  billing:
    image: bikeshare/bikesharing-billing:dev
    build:
      context: samples/BikeSharingApp/Billing

  gateway:
      image: bikeshare/bikesharing-gateway:dev
      build:
        context: samples/BikeSharingApp/Gateway

  reservation:
    image: bikeshare/bikesharing-reservation:dev
    build:
      context: samples/BikeSharingApp/Reservation

  reservationEngine:
      image: bikeshare/bikesharing-reservationengine:dev
      build:
        context: samples/BikeSharingApp/ReservationEngine
        dockerfile: Dockerfile.debug
  
  users:
    image: bikeshare/bikesharing-users:dev
    build:
      context: samples/BikeSharingApp/Users

  populateDatabase:
      image: bikeshare/bikesharing-populatedatabase:dev
      build:
        context: samples/BikeSharingApp/PopulateDatabase