version: '3.4' 

services:

  bikes:
    image: ${IMAGE_REPO:-bikeshare}/bikesharing-bikes:${IMAGE_TAG:-dev}
    build:
      context: samples/BikeSharingApp/Bikes

  bikeSharingWeb:
    image: ${IMAGE_REPO:-bikeshare}/bikesharing-bikesharingweb:${IMAGE_TAG:-dev}
    build:
      context: samples/BikeSharingApp/BikeSharingWeb
  
  billing:
    image: ${IMAGE_REPO:-bikeshare}/bikesharing-billing:${IMAGE_TAG:-dev}
    build:
      context: samples/BikeSharingApp/Billing

  gateway:
    image: ${IMAGE_REPO:-bikeshare}/bikesharing-gateway:${IMAGE_TAG:-dev}
    build:
      context: samples/BikeSharingApp/Gateway

  reservation:
    image: ${IMAGE_REPO:-bikeshare}/bikesharing-reservation:${IMAGE_TAG:-dev}
    build:
      context: samples/BikeSharingApp/Reservation

  reservationEngine:
    image: ${IMAGE_REPO:-bikeshare}/bikesharing-reservationengine:${IMAGE_TAG:-dev}
    build:
      context: samples/BikeSharingApp/ReservationEngine
      dockerfile: Dockerfile.debug

  users:
    image: ${IMAGE_REPO:-bikeshare}/bikesharing-users:${IMAGE_TAG:-dev}
    build:
      context: samples/BikeSharingApp/Users

  populateDatabase:
      image: ${IMAGE_REPO:-bikeshare}/bikesharing-populatedatabase:${IMAGE_TAG:-dev}
      build:
        context: samples/BikeSharingApp/PopulateDatabase