version: '3.4' 

services:

  bikes:
    image: azdspublic/bikesharing-bikes:build.20200723.1
    build:
      context: samples/BikeSharingApp/Bikes

  bikeSharingWeb:
      image: azdspublic/bikesharing-bikesharingweb:build.20200723.1
      build:
        context: samples/BikeSharingApp/BikeSharingWeb
  
  billing:
    image: azdspublic/bikesharing-billing:build.20200723.1
    build:
      context: samples/BikeSharingApp/Billing

  gateway:
      image: azdspublic/bikesharing-gateway:build.20200723.1
      build:
        context: samples/BikeSharingApp/Gateway

  reservation:
    image: azdspublic/bikesharing-reservation:build.20200723.1
    build:
      context: samples/BikeSharingApp/Reservation

  reservationEngine:
      image: azdspublic/bikesharing-reservationengine:build.20200723.1
      build:
        context: samples/BikeSharingApp/ReservationEngine
  
  users:
    image: azdspublic/bikesharing-users:build.20200723.1
    build:
      context: samples/BikeSharingApp/Users

  populateDatabase:
      image: azdspublic/bikesharing-populatedatabase:build.20200723.1
      build:
        context: samples/BikeSharingApp/PopulateDatabase