name: Bikes - Build All

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the images
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
        docker-compose push
      env:
        IMAGE_TAG: ${{ github.sha }}
        IMAGE_REPO: ghcr.io/${{ github.repository }}