name: Deploy Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The name of the environment to be deployed
        required: true
      component:
        description: The component to deploy
        required: true

env:
  rg-name: cd-mindaro
  cluster-name: cdmindaro
  namespace: bikeapp

jobs:
  build-container:
    name: Build component image
    runs-on: ubuntu-20.04

    steps:
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Calculate chart path
      id: component-lower
      run: |
        # calculate the path to the chart for this component
        compLower=$(echo $component | tr '[:upper:]' '[:lower:]')
        echo "::set-output name=lower-name::$compLower"
      env:
        component: ${{ github.event.inputs.component }}

    - name: Generate docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        context: samples/BikeSharingApp/${{ github.event.inputs.component }}/
        images: ghcr.io/${{ github.repository }}/bikesharing-${{ steps.component-lower.outputs.lower-name }}
        tags: |
          type=ref,event=tag
          type=ref,event=pr
          type=sha,event=branch,prefix=,suffix=,format=short
  
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-container
    name: Deploy component
    runs-on: ubuntu-20.04

    steps:
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.rg-name }}
        cluster-name: ${{ env.cluster-name }}

    - name: Calculate chart path
      id: chart-meta
      run: |
        compLower=$(echo $component | tr '[:upper:]' '[:lower:]')
        echo "::set-output name=lower-name::$compLower"

        path='./samples/BikeSharingApp/$component/charts/$compLower/'
        echo "::set-output name=chart-path::$path"

        echo "::set-output name=release-name::$component-$version"
      env:
        component: ${{ github.event.inputs.component }}
        version: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

    - uses: azure/k8s-bake@v2.2
      id: bake
      with:
        renderEngine: helm
        helm-version: latest
        helmChart: ${{ steps.chart-meta.outputs.chart-path }}
        silent: 'false'
        releaseName: ${{ steps.chart-meta.outputs.release-name }}
        overrides: |
          image.repository: ghcr.io/${{ github.repository }}/bikesharing-${{ steps.component-lower.outputs.lower-name }}
          image.tag: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          fullnameOverride: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
        
    - uses: azure/k8s-deploy@v1
      with:
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        namespace: ${{ env.namespace }}
        force: true